[package]
name = "scorch-pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

scorch-lang ={ git = "https://github.com/toolateralus/scorch-interpreter", branch = "lib"}
colored = "2.1.0"
git2 = "0.18.1"
indexmap = "2.1.0"

